name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Cache TypeScript
      uses: actions/cache@v3
      with:
        path: |
          .tsbuildinfo
          dist
        key: ${{ runner.os }}-typescript-${{ hashFiles('**/*.ts', '**/*.vue', 'tsconfig.json') }}
    
    - name: Cache ESLint
      uses: actions/cache@v3
      with:
        path: .eslintcache
        key: ${{ runner.os }}-eslint-${{ hashFiles('.eslintrc.js', '**/*.ts', '**/*.vue') }}
    
    - name: Install dependencies
      run: npm ci
      
    - name: Type check
      run: npm run type-check
      
    - name: Run unit tests
      run: npm run test:unit
      
    - name: Run linting
      run: npm run lint

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
    
    strategy:
      matrix:
        browser: [chromium]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run E2E tests
      run: npm run test:e2e -- --project=${{ matrix.browser }}
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.browser }}
        path: playwright-report/
        retention-days: 30